using System.Collections.Generic;

namespace IEGOFormationEditor.InazumaEleven.Common
{
    public static class Formations
    {
        public static Dictionary<string, string> Galaxy = new Dictionary<string, string>()
        {
            {"btl_fm0001", "F-Raimon"},
            {"btl_fm0002", "Lame noire"},
            {"btl_fm0003", "F-Basic"},
            {"btl_fm0004", "F-Stratosphere"},
            {"btl_fm0005", "F-Omnipresenc"},
            {"btl_fm0006", "F-Neo Death Zone"},
            {"btl_fm0007", "F-Lobster Claw"},
            {"btl_fm0008", "F-Moonlight"},
            {"btl_fm0009", "F-Avalanche"},
            {"btl_fm0010", "F-Tiger Strike"},
            {"btl_fm0011", "F-Phantom"},
            {"btl_fm0012", "F-Neo-Cloud"},
            {"btl_fm0013", "F-Divinity"},
            {"btl_fm0014", "F-One Thousand"},
            {"btl_fm0015", "F-Blue Leaves"},
            {"btl_fm0016", "F-Youthful Spirit"},
            {"btl_fm0017", "F-Shining Light"},
            {"btl_fm0018", "F-Ancient Power"},
            {"btl_fm0019", "F-Zero"},
            {"btl_fm0020", "F-Albatross"},
            {"btl_fm0021", "F-Legacy"},
            {"btl_fm0022", "F-Resistance"},
            {"btl_fm0023", "F-Defence Formation"},
            {"btl_fm0024", "F-Alpha"},
            {"btl_fm0025", "F-Antlers"},
            {"btl_fm0026", "F-Beta"},
            {"btl_fm0027", "F-Gamma"},
            {"btl_fm0028", "F-Terracotta"},
            {"btl_fm0029", "F-Zanark"},
            {"btl_fm0030", "F-Perfection"},
            {"btl_fm0031", "F-Zan"},
            {"btl_fm0032", "F-Gihl"},
            {"btl_fm0033", "F-Gahl"},
            {"btl_fm0034", "F-Ragnah"},
            {"btl_fm0035", "F-Full Moon"},
            {"btl_fm0036", "F-New Moo"},
            {"btl_fm0037", "F-Predator"},
            {"btl_fm0038", "F-Flower of Chaos"},
            {"btl_fm0039", "F-Lightning"},
            {"btl_fm0040", "F-Burning Soul"},
            {"btl_fm0041", "F-Ocean Dive"},
            {"btl_fm0042", "F-Sandstorm"},
            {"btl_fm0043", "F-Pakuchi Smell"},
            {"btl_fm0044", "F-Oasis Route"},
            {"btl_fm0045", "F-Coup d'État"},
            {"btl_fm0046", "F-Iron Shell"},
            {"btl_fm0047", "F-Grace Fin"},
            {"btl_fm0048", "F-Lost Wing"},
            {"btl_fm0049", "F-Hunters"},
            {"btl_fm0050", "F-Orbius"},
            {"btl_fm0051", "F-Black Hole"},
            {"btl_fm0052", "F-Big Bang"},
            {"btl_fm0053", "F-Supernova"},
            {"btl_fm0054", "F-Galaxy"},
            {"btl_fm0101", "B-Raimon"},
            {"btl_fm0102", "B-Flat Back"},
            {"btl_fm0103", "B-Cube"},
            {"btl_fm0104", "B-Train"},
            {"btl_fm0105", "B-Breakthrough"},
            {"btl_fm0106", "B-Diamond"},
            {"btl_fm0107", "B-Basic"},
            {"btl_fm0108", "B-Straight Line"},
            {"btl_fm0109", "B-Left Branch"},
            {"btl_fm0110", "B-Right Branch"},
            {"btl_fm0111", "B-Standard"},
        };
    }
}
